// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Panahgah.Api.Data;

#nullable disable

namespace Panahgah.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406192241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Panahgah.Api.Models.Donation", b =>
                {
                    b.Property<int>("donation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("donation_id"));

                    b.Property<decimal?>("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("campaign_name")
                        .HasColumnType("text");

                    b.Property<string>("channel_source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("created_by_partner_id")
                        .HasColumnType("integer");

                    b.Property<string>("currency_code")
                        .HasColumnType("text");

                    b.Property<DateOnly>("donation_date")
                        .HasColumnType("date");

                    b.Property<string>("donation_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("estimated_value")
                        .HasColumnType("numeric");

                    b.Property<string>("impact_unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_recurring")
                        .HasColumnType("boolean");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("referral_post_id")
                        .HasColumnType("integer");

                    b.Property<int>("supporter_id")
                        .HasColumnType("integer");

                    b.HasKey("donation_id");

                    b.HasIndex("created_by_partner_id");

                    b.HasIndex("referral_post_id");

                    b.HasIndex("supporter_id");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.DonationAllocation", b =>
                {
                    b.Property<int>("allocation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("allocation_id"));

                    b.Property<DateOnly>("allocation_date")
                        .HasColumnType("date");

                    b.Property<string>("allocation_notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("amount_allocated")
                        .HasColumnType("numeric");

                    b.Property<int>("donation_id")
                        .HasColumnType("integer");

                    b.Property<string>("program_area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("integer");

                    b.HasKey("allocation_id");

                    b.HasIndex("donation_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.EducationRecord", b =>
                {
                    b.Property<int>("education_record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("education_record_id"));

                    b.Property<decimal>("attendance_rate")
                        .HasColumnType("numeric");

                    b.Property<string>("attendance_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("completion_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("course_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("education_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("gpa_like_score")
                        .HasColumnType("numeric");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("program_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("progress_percent")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("record_date")
                        .HasColumnType("date");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.HasKey("education_record_id");

                    b.HasIndex("resident_id");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("health_record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("health_record_id"));

                    b.Property<decimal>("bmi")
                        .HasColumnType("numeric");

                    b.Property<bool>("dental_checkup_done")
                        .HasColumnType("boolean");

                    b.Property<decimal>("energy_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("general_health_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("height_cm")
                        .HasColumnType("numeric");

                    b.Property<bool>("medical_checkup_done")
                        .HasColumnType("boolean");

                    b.Property<string>("medical_notes_restricted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("nutrition_score")
                        .HasColumnType("numeric");

                    b.Property<bool>("psychological_checkup_done")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("record_date")
                        .HasColumnType("date");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("sleep_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("weight_kg")
                        .HasColumnType("numeric");

                    b.HasKey("health_record_id");

                    b.HasIndex("resident_id");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.HomeVisitation", b =>
                {
                    b.Property<int>("visitation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("visitation_id"));

                    b.Property<string>("family_cooperation_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("family_members_present")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("follow_up_needed")
                        .HasColumnType("boolean");

                    b.Property<string>("follow_up_notes")
                        .HasColumnType("text");

                    b.Property<string>("location_visited")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<bool>("safety_concerns_noted")
                        .HasColumnType("boolean");

                    b.Property<string>("social_worker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("visit_date")
                        .HasColumnType("date");

                    b.Property<string>("visit_outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("visit_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("visitation_id");

                    b.HasIndex("resident_id");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("item_id"));

                    b.Property<int>("donation_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("estimated_unit_value")
                        .HasColumnType("numeric");

                    b.Property<string>("intended_use")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("received_condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("unit_of_measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("item_id");

                    b.HasIndex("donation_id");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.IncidentReport", b =>
                {
                    b.Property<int>("incident_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("incident_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("follow_up_required")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("incident_date")
                        .HasColumnType("date");

                    b.Property<string>("incident_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reported_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("resolution_date")
                        .HasColumnType("date");

                    b.Property<bool>("resolved")
                        .HasColumnType("boolean");

                    b.Property<string>("response_taken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("integer");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("incident_id");

                    b.HasIndex("resident_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.InterventionPlan", b =>
                {
                    b.Property<int>("plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("plan_id"));

                    b.Property<DateOnly?>("case_conference_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("plan_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plan_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<string>("services_provided")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("target_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("target_value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("plan_id");

                    b.HasIndex("resident_id");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.Partner", b =>
                {
                    b.Property<int>("partner_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("partner_id"));

                    b.Property<string>("contact_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("partner_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("partner_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("partner_id");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("assignment_id"));

                    b.Property<DateOnly?>("assignment_end")
                        .HasColumnType("date");

                    b.Property<DateOnly>("assignment_start")
                        .HasColumnType("date");

                    b.Property<bool>("is_primary")
                        .HasColumnType("boolean");

                    b.Property<int>("partner_id")
                        .HasColumnType("integer");

                    b.Property<string>("program_area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("responsibility_notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("safehouse_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("assignment_id");

                    b.HasIndex("partner_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.ProcessRecording", b =>
                {
                    b.Property<int>("recording_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("recording_id"));

                    b.Property<bool>("concerns_flagged")
                        .HasColumnType("boolean");

                    b.Property<string>("emotional_state_end")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emotional_state_observed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("follow_up_actions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("interventions_applied")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notes_restricted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("progress_noted")
                        .HasColumnType("boolean");

                    b.Property<bool>("referral_made")
                        .HasColumnType("boolean");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("session_date")
                        .HasColumnType("date");

                    b.Property<int>("session_duration_minutes")
                        .HasColumnType("integer");

                    b.Property<string>("session_narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("session_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("social_worker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("recording_id");

                    b.HasIndex("resident_id");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("snapshot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("snapshot_id"));

                    b.Property<string>("headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_published")
                        .HasColumnType("boolean");

                    b.Property<string>("metric_payload_json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("published_at")
                        .HasColumnType("date");

                    b.Property<DateOnly>("snapshot_date")
                        .HasColumnType("date");

                    b.Property<string>("summary_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("snapshot_id");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.Resident", b =>
                {
                    b.Property<int>("resident_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("resident_id"));

                    b.Property<string>("age_upon_admission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assigned_social_worker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("birth_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("case_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("case_control_no")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("case_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("current_risk_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("date_case_study_prepared")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_closed")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_colb_obtained")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_colb_registered")
                        .HasColumnType("date");

                    b.Property<DateOnly>("date_enrolled")
                        .HasColumnType("date");

                    b.Property<DateOnly>("date_of_admission")
                        .HasColumnType("date");

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<bool>("family_indigenous")
                        .HasColumnType("boolean");

                    b.Property<bool>("family_informal_settler")
                        .HasColumnType("boolean");

                    b.Property<bool>("family_is_4ps")
                        .HasColumnType("boolean");

                    b.Property<bool>("family_parent_pwd")
                        .HasColumnType("boolean");

                    b.Property<bool>("family_solo_parent")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_special_needs")
                        .HasColumnType("boolean");

                    b.Property<string>("initial_case_assessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("initial_risk_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("internal_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_pwd")
                        .HasColumnType("boolean");

                    b.Property<string>("length_of_stay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notes_restricted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("place_of_birth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("present_age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pwd_type")
                        .HasColumnType("text");

                    b.Property<string>("referral_source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("referring_agency_person")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reintegration_status")
                        .HasColumnType("text");

                    b.Property<string>("reintegration_type")
                        .HasColumnType("text");

                    b.Property<string>("religion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("integer");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("special_needs_diagnosis")
                        .HasColumnType("text");

                    b.Property<bool>("sub_cat_at_risk")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_child_labor")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_child_with_hiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_cicl")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_orphaned")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_osaec")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_physical_abuse")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_sexual_abuse")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_street_child")
                        .HasColumnType("boolean");

                    b.Property<bool>("sub_cat_trafficked")
                        .HasColumnType("boolean");

                    b.HasKey("resident_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.Safehouse", b =>
                {
                    b.Property<int>("safehouse_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("safehouse_id"));

                    b.Property<int>("capacity_girls")
                        .HasColumnType("integer");

                    b.Property<int>("capacity_staff")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("current_occupancy")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("open_date")
                        .HasColumnType("date");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("safehouse_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("safehouse_id");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("metric_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("metric_id"));

                    b.Property<int>("active_residents")
                        .HasColumnType("integer");

                    b.Property<decimal>("avg_education_progress")
                        .HasColumnType("numeric");

                    b.Property<decimal>("avg_health_score")
                        .HasColumnType("numeric");

                    b.Property<int>("home_visitation_count")
                        .HasColumnType("integer");

                    b.Property<int>("incident_count")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("month_end")
                        .HasColumnType("date");

                    b.Property<DateOnly>("month_start")
                        .HasColumnType("date");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("process_recording_count")
                        .HasColumnType("integer");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("integer");

                    b.HasKey("metric_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("post_id"));

                    b.Property<int?>("avg_view_duration_seconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("boost_budget_php")
                        .HasColumnType("numeric");

                    b.Property<string>("call_to_action_type")
                        .HasColumnType("text");

                    b.Property<string>("campaign_name")
                        .HasColumnType("text");

                    b.Property<string>("caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("caption_length")
                        .HasColumnType("integer");

                    b.Property<int>("click_throughs")
                        .HasColumnType("integer");

                    b.Property<int>("comments")
                        .HasColumnType("integer");

                    b.Property<string>("content_topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("day_of_week")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("donation_referrals")
                        .HasColumnType("integer");

                    b.Property<decimal>("engagement_rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("estimated_donation_value_php")
                        .HasColumnType("numeric");

                    b.Property<bool>("features_resident_story")
                        .HasColumnType("boolean");

                    b.Property<int>("follower_count_at_post")
                        .HasColumnType("integer");

                    b.Property<int?>("forwards")
                        .HasColumnType("integer");

                    b.Property<bool>("has_call_to_action")
                        .HasColumnType("boolean");

                    b.Property<string>("hashtags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("impressions")
                        .HasColumnType("integer");

                    b.Property<bool>("is_boosted")
                        .HasColumnType("boolean");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.Property<string>("media_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("mentions_count")
                        .HasColumnType("integer");

                    b.Property<int>("num_hashtags")
                        .HasColumnType("integer");

                    b.Property<string>("platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("platform_post_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("post_hour")
                        .HasColumnType("integer");

                    b.Property<string>("post_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("post_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("profile_visits")
                        .HasColumnType("integer");

                    b.Property<int>("reach")
                        .HasColumnType("integer");

                    b.Property<int>("saves")
                        .HasColumnType("integer");

                    b.Property<string>("sentiment_tone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("shares")
                        .HasColumnType("integer");

                    b.Property<int?>("subscriber_count_at_post")
                        .HasColumnType("integer");

                    b.Property<int?>("video_views")
                        .HasColumnType("integer");

                    b.Property<int?>("watch_time_seconds")
                        .HasColumnType("integer");

                    b.HasKey("post_id");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.Supporter", b =>
                {
                    b.Property<int>("supporter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("supporter_id"));

                    b.Property<string>("acquisition_channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("first_donation_date")
                        .HasColumnType("date");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("organization_name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("relationship_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("supporter_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("supporter_id");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("Panahgah.Api.Models.Donation", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Partner", "created_by_partner")
                        .WithMany("donations_created")
                        .HasForeignKey("created_by_partner_id");

                    b.HasOne("Panahgah.Api.Models.SocialMediaPost", "referral_post")
                        .WithMany("referred_donations")
                        .HasForeignKey("referral_post_id");

                    b.HasOne("Panahgah.Api.Models.Supporter", "supporter")
                        .WithMany("donations")
                        .HasForeignKey("supporter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("created_by_partner");

                    b.Navigation("referral_post");

                    b.Navigation("supporter");
                });

            modelBuilder.Entity("Panahgah.Api.Models.DonationAllocation", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Donation", "donation")
                        .WithMany("donation_allocations")
                        .HasForeignKey("donation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Panahgah.Api.Models.Safehouse", "safehouse")
                        .WithMany("donation_allocations")
                        .HasForeignKey("safehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donation");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("Panahgah.Api.Models.EducationRecord", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("education_records")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("Panahgah.Api.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("health_wellbeing_records")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("Panahgah.Api.Models.HomeVisitation", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("home_visitations")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("Panahgah.Api.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Donation", "donation")
                        .WithMany("in_kind_donation_items")
                        .HasForeignKey("donation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donation");
                });

            modelBuilder.Entity("Panahgah.Api.Models.IncidentReport", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("incident_reports")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Panahgah.Api.Models.Safehouse", "safehouse")
                        .WithMany("incident_reports")
                        .HasForeignKey("safehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("Panahgah.Api.Models.InterventionPlan", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("intervention_plans")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("Panahgah.Api.Models.PartnerAssignment", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Partner", "partner")
                        .WithMany("partner_assignments")
                        .HasForeignKey("partner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Panahgah.Api.Models.Safehouse", "safehouse")
                        .WithMany("partner_assignments")
                        .HasForeignKey("safehouse_id");

                    b.Navigation("partner");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("Panahgah.Api.Models.ProcessRecording", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Resident", "resident")
                        .WithMany("process_recordings")
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Resident", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Safehouse", "safehouse")
                        .WithMany("residents")
                        .HasForeignKey("safehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("Panahgah.Api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Panahgah.Api.Models.Safehouse", "safehouse")
                        .WithMany("safehouse_monthly_metrics")
                        .HasForeignKey("safehouse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Donation", b =>
                {
                    b.Navigation("donation_allocations");

                    b.Navigation("in_kind_donation_items");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Partner", b =>
                {
                    b.Navigation("donations_created");

                    b.Navigation("partner_assignments");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Resident", b =>
                {
                    b.Navigation("education_records");

                    b.Navigation("health_wellbeing_records");

                    b.Navigation("home_visitations");

                    b.Navigation("incident_reports");

                    b.Navigation("intervention_plans");

                    b.Navigation("process_recordings");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Safehouse", b =>
                {
                    b.Navigation("donation_allocations");

                    b.Navigation("incident_reports");

                    b.Navigation("partner_assignments");

                    b.Navigation("residents");

                    b.Navigation("safehouse_monthly_metrics");
                });

            modelBuilder.Entity("Panahgah.Api.Models.SocialMediaPost", b =>
                {
                    b.Navigation("referred_donations");
                });

            modelBuilder.Entity("Panahgah.Api.Models.Supporter", b =>
                {
                    b.Navigation("donations");
                });
#pragma warning restore 612, 618
        }
    }
}
