/** Shapes match ASP.NET Core JSON (camelCase for ConfirmDelete; snake_case from C# DTOs). */

export type Safehouse = {
  safehouse_id: number;
  safehouse_code: string;
  name: string;
  region: string;
  city: string;
  province: string;
  country: string;
  open_date: string;
  status: string;
  capacity_girls: number;
  capacity_staff: number;
  current_occupancy: number;
  notes: string;
};

export type Resident = {
  resident_id: number;
  case_control_no: string;
  internal_code: string;
  safehouse_id: number;
  case_status: string;
  sex: string;
  date_of_birth: string;
  birth_status: string;
  place_of_birth: string;
  religion: string;
  case_category: string;
  sub_cat_orphaned: boolean;
  sub_cat_trafficked: boolean;
  sub_cat_child_labor: boolean;
  sub_cat_physical_abuse: boolean;
  sub_cat_sexual_abuse: boolean;
  sub_cat_osaec: boolean;
  sub_cat_cicl: boolean;
  sub_cat_at_risk: boolean;
  sub_cat_street_child: boolean;
  sub_cat_child_with_hiv: boolean;
  is_pwd: boolean;
  pwd_type: string | null;
  has_special_needs: boolean;
  special_needs_diagnosis: string | null;
  family_is_4ps: boolean;
  family_solo_parent: boolean;
  family_indigenous: boolean;
  family_parent_pwd: boolean;
  family_informal_settler: boolean;
  date_of_admission: string;
  age_upon_admission: string;
  present_age: string;
  length_of_stay: string;
  referral_source: string;
  referring_agency_person: string;
  date_colb_registered: string | null;
  date_colb_obtained: string | null;
  assigned_social_worker: string;
  initial_case_assessment: string;
  date_case_study_prepared: string | null;
  reintegration_type: string | null;
  reintegration_status: string | null;
  initial_risk_level: string;
  current_risk_level: string;
  date_enrolled: string;
  date_closed: string | null;
  created_at: string;
  notes_restricted: string;
};

export type ResidentUpsertPayload = {
  case_control_no: string;
  internal_code: string;
  safehouse_id: number;
  case_status: string;
  sex: string;
  date_of_birth: string;
  birth_status: string;
  place_of_birth: string;
  religion: string;
  case_category: string;
  sub_cat_orphaned: boolean;
  sub_cat_trafficked: boolean;
  sub_cat_child_labor: boolean;
  sub_cat_physical_abuse: boolean;
  sub_cat_sexual_abuse: boolean;
  sub_cat_osaec: boolean;
  sub_cat_cicl: boolean;
  sub_cat_at_risk: boolean;
  sub_cat_street_child: boolean;
  sub_cat_child_with_hiv: boolean;
  is_pwd: boolean;
  pwd_type: string | null;
  has_special_needs: boolean;
  special_needs_diagnosis: string | null;
  family_is_4ps: boolean;
  family_solo_parent: boolean;
  family_indigenous: boolean;
  family_parent_pwd: boolean;
  family_informal_settler: boolean;
  date_of_admission: string;
  age_upon_admission: string;
  present_age: string;
  length_of_stay: string;
  referral_source: string;
  referring_agency_person: string;
  date_colb_registered: string | null;
  date_colb_obtained: string | null;
  assigned_social_worker: string;
  initial_case_assessment: string;
  date_case_study_prepared: string | null;
  reintegration_type: string | null;
  reintegration_status: string | null;
  initial_risk_level: string;
  current_risk_level: string;
  date_enrolled: string;
  date_closed: string | null;
  notes_restricted: string;
};

export type ProcessRecording = {
  recording_id: number;
  resident_id: number;
  session_date: string;
  social_worker: string;
  session_type: string;
  session_duration_minutes: number;
  emotional_state_observed: string;
  emotional_state_end: string;
  session_narrative: string;
  interventions_applied: string;
  follow_up_actions: string;
  progress_noted: boolean;
  concerns_flagged: boolean;
  referral_made: boolean;
  notes_restricted: string;
};

export type ProcessRecordingUpsertPayload = {
  resident_id: number;
  session_date: string;
  social_worker: string;
  session_type: string;
  session_duration_minutes: number;
  emotional_state_observed: string;
  emotional_state_end: string;
  session_narrative: string;
  interventions_applied: string;
  follow_up_actions: string;
  progress_noted: boolean;
  concerns_flagged: boolean;
  referral_made: boolean;
  notes_restricted: string;
};

export type SocialMediaPost = {
  post_id: number;
  platform: string;
  day_of_week: string;
  post_hour: number;
  post_type: string;
  media_type: string;
  caption: string;
  hashtags: string;
  num_hashtags: number;
  mentions_count: number;
  has_call_to_action: boolean;
  call_to_action_type: string | null;
  content_topic: string;
  sentiment_tone: string;
  caption_length: number;
  features_resident_story: boolean;
  campaign_name: string | null;
  is_boosted: boolean;
  boost_budget_php: number | null;
  donation_referrals: number;
  created_at: string;
};
